-- MySQL Script generated by MySQL Workbench
-- Wed Jan 11 11:07:36 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema trab_finalbd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema trab_finalbd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `trab_finalbd` DEFAULT CHARACTER SET utf8 ;
USE `trab_finalbd` ;

-- -----------------------------------------------------
-- Table `trab_finalbd`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Usuario` (
  `idUsuario` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idUsuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Estado`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Estado` (
  `idEstado` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idEstado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Cidade` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `fk_idEstado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `fk_idEstado_idx` (`fk_idEstado` ASC) VISIBLE,
  CONSTRAINT `fk_idEstado`
    FOREIGN KEY (`fk_idEstado`)
    REFERENCES `trab_finalbd`.`Estado` (`idEstado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Zona` (
  `idZona` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `fk_idCidade` INT NOT NULL,
  PRIMARY KEY (`idZona`),
  INDEX `fk_idCidade_idx` (`fk_idCidade` ASC) VISIBLE,
  CONSTRAINT `fk_idCidade`
    FOREIGN KEY (`fk_idCidade`)
    REFERENCES `trab_finalbd`.`Cidade` (`idCidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Secao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Secao` (
  `idSecao` INT NOT NULL AUTO_INCREMENT,
  `numero` INT NOT NULL,
  `fk_idZona` INT NOT NULL,
  PRIMARY KEY (`idSecao`),
  INDEX `fk_idZona_idx` (`fk_idZona` ASC) VISIBLE,
  CONSTRAINT `fk_idZona`
    FOREIGN KEY (`fk_idZona`)
    REFERENCES `trab_finalbd`.`Zona` (`idZona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Partido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Partido` (
  `idPartido` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPartido`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Cargo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Cargo` (
  `idCargo` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCargo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Candidato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Candidato` (
  `idCandidato` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NOT NULL,
  `fk_idPartido` INT NOT NULL,
  `fk_idCargo` INT NOT NULL,
  PRIMARY KEY (`idCandidato`),
  INDEX `fk_idPartido_idx` (`fk_idPartido` ASC) VISIBLE,
  INDEX `fk_idCargo_idx` (`fk_idCargo` ASC) VISIBLE,
  CONSTRAINT `fk_idPartido`
    FOREIGN KEY (`fk_idPartido`)
    REFERENCES `trab_finalbd`.`Partido` (`idPartido`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idCargo`
    FOREIGN KEY (`fk_idCargo`)
    REFERENCES `trab_finalbd`.`Cargo` (`idCargo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Votos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Votos` (
  `idVotos` INT NOT NULL AUTO_INCREMENT,
  `num_votos` INT NOT NULL,
  `turno` TINYINT NOT NULL,
  `ano` INT NOT NULL,
  `fk_idSecao` INT NOT NULL,
  `fk_idCandidato` INT NOT NULL,
  `fk_idUsuario` INT NOT NULL,
  PRIMARY KEY (`idVotos`),
  INDEX `fk_idSecao_idx` (`fk_idSecao` ASC) VISIBLE,
  INDEX `fk_idCandidato_idx` (`fk_idCandidato` ASC) VISIBLE,
  INDEX `fk_idUsuario_idx` (`fk_idUsuario` ASC) VISIBLE,
  CONSTRAINT `fk_idSecao`
    FOREIGN KEY (`fk_idSecao`)
    REFERENCES `trab_finalbd`.`Secao` (`idSecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idCandidato`
    FOREIGN KEY (`fk_idCandidato`)
    REFERENCES `trab_finalbd`.`Candidato` (`idCandidato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idUsuario`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `trab_finalbd`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `trab_finalbd`.`Boletim`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `trab_finalbd`.`Boletim` (
  `idBoletim` INT NOT NULL AUTO_INCREMENT,
  `foto` BLOB NOT NULL,
  `fk_idUsuario` INT NOT NULL,
  `fk_idSecao` INT NOT NULL,
  PRIMARY KEY (`idBoletim`),
  INDEX `fk_idUsuario_idx` (`fk_idUsuario` ASC) VISIBLE,
  INDEX `fk_idSecao_idx` (`fk_idSecao` ASC) VISIBLE,
  CONSTRAINT `fk_idUsuario`
    FOREIGN KEY (`fk_idUsuario`)
    REFERENCES `trab_finalbd`.`Usuario` (`idUsuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_idSecao`
    FOREIGN KEY (`fk_idSecao`)
    REFERENCES `trab_finalbd`.`Secao` (`idSecao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
